# Generated by Django 3.2 on 2021-04-29 07:47

import apps.books.vaidators
import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, validators=[apps.books.vaidators.NameValidator()])),
                ('address', models.CharField(max_length=100, validators=[apps.books.vaidators.AddressValidator()])),
                ('phone_number', models.CharField(max_length=10, validators=[apps.core.validators.PhoneNumberValidator])),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, validators=[apps.books.vaidators.NameValidator()])),
                ('edition', models.CharField(max_length=100)),
                ('available_books', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[apps.books.vaidators.NameValidator()])),
                ('address', models.CharField(max_length=100, validators=[apps.books.vaidators.AddressValidator()])),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[apps.core.validators.PhoneNumberValidator])),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BookBorrow',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('date_borrowed', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('number_of_days_issued', models.PositiveIntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
