# Generated by Django 3.2 on 2021-04-28 23:34

import apps.books.vaidators
import apps.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, validators=[apps.books.vaidators.NameValidator()])),
                ('address', models.CharField(max_length=100, validators=[apps.books.vaidators.AddressValidator()])),
                ('phone_number', models.CharField(max_length=10, validators=[apps.core.validators.PhoneNumberValidator])),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, validators=[apps.books.vaidators.NameValidator()])),
                ('edition', models.CharField(max_length=100)),
                ('available_books', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, validators=[apps.books.vaidators.NameValidator()])),
                ('address', models.CharField(max_length=100, validators=[apps.books.vaidators.AddressValidator()])),
                ('phone_number', models.CharField(max_length=10, validators=[apps.core.validators.PhoneNumberValidator])),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BookBorrow',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('date_borrowed', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('fine_amount', models.PositiveIntegerField()),
                ('number_of_days_issued', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='books.publication'),
        ),
        migrations.AddField(
            model_name='author',
            name='publication',
            field=models.ManyToManyField(to='books.Publication'),
        ),
        migrations.AddConstraint(
            model_name='bookborrow',
            constraint=models.UniqueConstraint(fields=('book', 'user'), name='unique book for user'),
        ),
    ]
