# Generated by Django 3.2 on 2021-04-28 23:47

import apps.books.vaidators
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[apps.books.vaidators.NameValidator()]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[apps.core.validators.PhoneNumberValidator]),
        ),
    ]
