# Generated by Django 3.2 on 2021-04-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookborrow',
            name='number_of_days_issued',
        ),
    ]
