# Generated by Django 3.2 on 2021-04-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_bookborrow_number_of_days_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrow',
            name='number_of_days_issued',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
