# Generated by Django 3.2 on 2021-04-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210429_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookborrow',
            name='number_of_days_issued',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
