# Generated by Django 3.2 on 2021-04-30 07:15

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookborrow_number_of_days_issued'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReturn',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('actual_return_date', models.DateTimeField()),
                ('actual_days_issued_days', models.DurationField()),
                ('book_borrowed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.bookborrow')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
