# Generated by Django 3.2 on 2021-04-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookreturn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreturn',
            old_name='actual_return_date',
            new_name='returned_date',
        ),
        migrations.AlterField(
            model_name='bookreturn',
            name='actual_days_issued_days',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
