# Generated by Django 3.2 on 2021-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210430_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreturn',
            name='fine_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
