# Generated by Django 3.2 on 2021-04-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_bookreturn_fine_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreturn',
            name='overdue_days',
        ),
    ]
