# Generated by Django 3.2 on 2021-04-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_bookreturn_overdue_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreturn',
            old_name='actual_days_issued_days',
            new_name='actual_issued_days',
        ),
    ]
