# Generated by Django 3.2 on 2021-05-04 03:34

import apps.books.vaidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_rename_actual_days_issued_days_bookreturn_actual_issued_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[apps.books.vaidators.NameValidator()]),
        ),
    ]
